# 工作流名称
name: Sync-Images-to-Lesso-Harbor
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Lesso Harbor.
# 怎样触发工作流
on:
  push:
    branches: [ "lesso-harbor" ]
  pull_request:
    branches: [ "lesso-harbor" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常包含一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Lesso Harbor
      uses: docker/login-action@v2.2.0
      with:
        registry: harbor.prod.k8s.lesso.com
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Lesso Harbor
      run: |
        #!/usr/bin/env bash
        while IFS= read -r image; do
          skopeo copy "docker://$image" "docker://harbor.prod.k8s.lesso.com/istio/$(basename "$image")"
        done < image_list.txt